### ISSUE TITLE
Errors with offsets

### ISSUE THREAD

**Issue by PlzHelpPlz** [alxbrn/r6s-external-example#3]
I get errors with offsets:
OFFSET_ENTITY
OFFSET_ENTITY_PLAYERINFO_DEREF
OFFSET_ENTITY_REF
OFFSET_PLAYERINFO_NAME
OFFSET_PLAYERINFO_TEAMID
What should I do

**Comment by JayneFrack** [comment]
Same Problem

**Comment by alxbrn** [comment]
Update the offsets.
