### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by JayneFrack** [alxbrn/r6s-external-example#4]
Hi when I try to build I get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _Direct3DCreate9@4 referenced in function "public: void __thiscall Overlay::InitD3D(struct HWND__ *)" (?InitD3D@Overlay@@QAEXPAUHWND__@@@Z)	Final	C:\Users\Admin\OneDrive\Desktop\r6ss\R6S-External-master\R6S-External\Final\Overlay.obj	1	

What am I supposed to do?

**Comment by alxbrn** [comment]
You are missing some linker imports. Google june 2010 directx sdk for further information.
